%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.00975251162  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 0.0021280256   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 0.00135568192     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 7.111367e-05       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: "/imu"
